### ISSUE TITLE
Broken link to the Control Plane

### ISSUE THREAD

**Issue by ramonh** [suborbital/docs#156]
When looking at the section on [Executing Functions](https://docs.suborbital.dev/compute/quickstart/write-functions#executing-functions), "Control Plane" links to this url:
https://docs.suborbital.dev/concepts/data-plane-vs-control-plane#control-plane

Which doesn't exist.

Could it be this is due to sites moving?

**Comment by LauraLangdon** [comment]
This will be resolved by PR# https://github.com/suborbital/docs/pull/155
