### ISSUE TITLE
Shrink website/docs/assets/editor-screen.png ?

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#165]
See https://github.com/suborbital/docs/pull/155#pullrequestreview-1074226752:

> The website/docs/assets/editor-screen.png image still seems huge (over 300k!)... I think we should crop it further, reduce its resolution, and send it through a compressor.

I'm concerned that if it's smaller or lower res it'll be impossible to read. If it doesn't need to be easy to read, I could just remove it instead!

**Comment by flaki** [comment]
Oops, just saw this. I believe [this](https://github.com/suborbital/docs/pull/155#issuecomment-1219836823) shall resolve the issue.

**Comment by LauraLangdon** [comment]
Closed by https://github.com/suborbital/docs/pull/155#issuecomment-1219836823

**Comment by callahad** [comment]
Looks like 2f6c13787ef8bbb53acff87d142ed480a8f4ca17 pulled in the 68 KB version from Flaki's comment, rather than the [further reduction](https://github.com/suborbital/docs/pull/155#issuecomment-1219914648) to 28 KB... since the asset is already there, might as well put in the Even Smaller one.

**Comment by LauraLangdon** [comment]
> Looks like [2f6c137](https://github.com/suborbital/docs/commit/2f6c13787ef8bbb53acff87d142ed480a8f4ca17) pulled in the 68 KB version from Flaki's comment, rather than the [further reduction](https://github.com/suborbital/docs/pull/155#issuecomment-1219914648) to 28 KB... since the asset is already there, might as well put in the Even Smaller one.


Ah, I'd used that because I thought I'd understood from [Flaki's comment](https://github.com/suborbital/docs/pull/155#issuecomment-1219836823) that it was optimized for retina screens, so kind of a lim sup: the smallest size that would still look good on large screens. 

> It should be roughly ~66KB now, it is a 934x525px@2x image (for retina screens)...

I'll definitely redo it if I misunderstood, ofc @callahad!

**Comment by callahad** [comment]
Yep! The 28 KB version is exactly the same resolution as Flaki's (and thus equally suitable for retina screens), but compressed slightly more efficiently (8-bit pallet, etc.)

**Comment by LauraLangdon** [comment]
> Yep! The 28 KB version is exactly the same resolution as Flaki's (and thus equally suitable for retina screens), but compressed slightly more efficiently (8-bit pallet, etc.)

Got i!
