### ISSUE TITLE
Atmo: background links to the wrong SUFA blog post

### ISSUE THREAD

**Issue by javorszky** [suborbital/docs#17]
In the atmo / more info / background article there's a link to the SUFA design pattern documentation which currently links to https://blog.suborbital.dev/how-to-familiarize-yourself-with-a-new-codebase

I think it is supposed to link to https://blog.suborbital.dev/building-a-better-monolith? @cohix can you double check my assumption? :)

**Comment by ramonh** [comment]
Solved in #83
