### ISSUE TITLE
Sat docs starter

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#19]
We should get an initial documentation scaffolded for [sat](https://github.com/suborbital/sat/#readme). The docs should contain the README content, and an appropriate structuring, during which we should discover the missing content requirements.

We should have information on how to run sat (baremetal/docker deployments), as well as some information about the one-shot runnable executor engine usecase.

**Comment by LauraLangdon** [comment]
I believe the [sat section in the docs](https://docs.suborbital.dev/sat/) and the R[EADME on the sat repo](https://github.com/suborbital/sat/#readme) close this issue.
