### ISSUE TITLE
Revisions from Taryn's walkthrough

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#196]
@tarynmusgrave went through the new docs and had super helpful feedback! 🙏

edit: since Subo's being deprecated some of these are now "won't fix" (in strikethrough)

- [x] Need to document how to upgrade Subo
- [x] Fix weird wording in the danger box: "and would like locally develop”
- [x] “Next, use Subo to start your local SE2 instance. Make sure to do this within the same directory you created above! You can verify that you're in the correct directory by verifying that it contains the docker-compose.yaml file.”
  - "I have no idea which directory I am in / was in. Which directory should I be in? Or is it something to do with docker being connected?"
    - Yes, we should specify that Docker needs to be running already.
- [x] ~~"I still don’t understand the docker-compose.yaml bit since i couldnt see that file in the location i was already in but hey."~~
- [x] Note that `subo se2 deploy --local` takes a while!
  - ~~Maybe some CLI "hold music"? Not actual audio but text? I think maybe @tarynmusgrave told me Redwood does this.~~
- [x] ~~"Be nice if the docs told me to follow the instructions on the cli. What i am trying to do here? Should i be going to the website it gives me in the cli? Why?"~~
- [x] ~~"Obtain an editor token - Should i open a new terminal window or am I okay to exit out of the SE2 Locally section (where it asks me to choose another option)"~~
- [x] “In addition to the IDENTIFIER and ACCESS_KEY, you’ll also need to set NAMESPACE and fn to the name of our namespace (e.g. default) and the name of our plugin (e.g. foo). Copy the token field in the response.”
  - "It says our plugin e.g foo but we just used the example hello in the previous step so this should be e.g hello and use the data from above. Is our namespace default or did we change it earlier? Can we?"
 - [x] “Copy the token field in the response”. What is that? Does it translate to ACCESS_KEY?
   - Looks like the changes I made to make these be `ENVIRONMENT_TOKEN` got reverted when the code snippets were updated.
- [x] curl --location --request GET "http://local.suborbital.network:8082/auth/v2/access/${IDENTIFIER}/${NAMESPACE}/${EXT}\--headerAuthorization:Bearer${ACCESS_KEY}"
  - "What are these, with examples from the previous step."
    - IDENTIFIER (need to add context back for this, but also https://github.com/suborbital/se2/issues/905)
    - NAMESPACE (need to add context back for this)
    - EXT (should be `FN`)
    - ACCESS_KEY: token? (yes, `ENVIRONMENT_TOKEN`)
- [x] ~~Editor URLs in production https://editor.suborbital.network/?builder=https://yourbuilder.example.com&ident=dev.suborbital.user1&fn=my-plugin&template=javascript~~
  - ~~"Again I think this link should match every step we have done up until now. Where is hello?"~~

**Comment by tarynmusgrave** [comment]
> Note that subo se2 deploy --local takes a while!
> Maybe some CLI "hold music"? Not actual audio but text? I think maybe @tarynmusgrave told me Redwood does this.

Haha yes they do and it is lovely. They say..... go for a walk, have a coffee, build a house haha its cute.
