### ISSUE TITLE
Editor is not configured notice has broken link to documentation

### ISSUE THREAD

**Issue by javorszky** [suborbital/docs#208]
## What I did

Visit https://editor.suborbital.network

Got the following notice:
<img width="860" alt="notice" src="https://user-images.githubusercontent.com/1196299/226633745-0065bffb-f6e0-4008-9561-4567dc01d1b7.png">

That notice has a link to documentation. Link href is https://docs.suborbital.dev/compute/integrate-the-function-editor/code-editor/#configuration

## What I expected to happen

Clicking the link should have taken me to a documentation where I can read about the required query params (maybe even an interactive builder that would give me a built link based on the inputs in boxes)

## What happened instead?

Got a 404
<img width="825" alt="404" src="https://user-images.githubusercontent.com/1196299/226634264-85b2e8a5-3c9a-4578-a5d8-2d6b8f2b839c.png">

**Comment by LauraLangdon** [comment]
Fixing the link probably needs to happen in the editor itself, not the docs, and it should be this link: https://docs.suborbital.dev/how-to/customize-plugins/plugin-editor﻿
﻿
But now that I think about it, this page needs to be updated with the new terms and possibly more. I'll comb through it. Tracking here: https://github.com/suborbital/docs/pull/209

**Comment by LauraLangdon** [comment]
Closing in favor of https://github.com/suborbital/se2/pull/1168
