### ISSUE TITLE
List supported languages for Runnables

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#22]
There should be a list of supported languages in **Concepts → Runnables**, e.g. under a new heading (so it can be directly referenced). We should list all languages with full support, beta or experimental support separately.

In **Usage → Creating runnables** we should reference this page for possible values of the `--lang` parameter.

**Comment by LauraLangdon** [comment]
@flaki Is there a way I can refer to the support status of a language using whatever is displaying that info in the images below?

![image](https://user-images.githubusercontent.com/48335772/158731016-6839791f-2eaf-47f2-8850-5bfabd7acc06.png)

![image](https://user-images.githubusercontent.com/48335772/158731043-e187f17b-cab1-43b2-a464-e6a359d4414e.png)

It looks like it should be something to do with the `MultiLanguageCodeBlock` but I'm not sure how to reference the status without generating a whole code block. I'm looking at the [declaration for it](https://github.com/suborbital/docs/blob/main/website/extensions/mlc.jsx) and I don't know JS or React well enough to figure out how to refer to just the status. I think maybe the statuses are aggregated in the `getCodeBlockLangs` function?

**Comment by flaki** [comment]
Oh but this page already exists!
https://docs.suborbital.dev/reactr/language-support/

One things it's still missing though, is this part:

> In **Usage → Creating runnables** we should reference this page for possible values of the `--lang` parameter.

That said, to answer your question, currently these badges are sort of hacked into `MultiLanguageCodeBlock`, and I had plans to make them their own components (and with that, make them available separately) but haven't gotten to it yet. I'll file an issue for that separately so that we can track that!

@LauraLangdon do you think you could look into `subo`'s `--lang` values and add the corresponding values to the language support page above (somewhere where it's appropriate, I'll leave the formatting to you) that we can close this issue? That page is a little stubby anyway so much more updates will come as we continue documenting our runnable language support!
