### ISSUE TITLE
Nitpicks / Tweaks for NewDocs launch

### ISSUE THREAD

**Issue by cohix** [suborbital/docs#30]
- [x] Let's update `Atmo will be gaining a secrets management system in 2021.` ?

- [ ] Let's change `By default, Rust will be used. To use Swift, pass --lang` to instead use JavaScript as the alternative?

- [x] Let's remove `To start, Atmo supports handlers for HTTP requests, particulary designed to help building web APIs.`

- [x] `The as and with clauses shown above will be discussed next.` links to the 'Managing state' page, which is not actually next in the list.

- [x] Let's change the `Building a bundle` page title to instead be `Build your application`

- [x] Let's remove `To learn how to operate Atmo in real-world scenarios.`

- [x] Let's change `Atmo is still in early Beta, and as such should not yet be used for production workloads.` to `Atmo is in beta, and is suitable production workloads. If you're using Atmo in production, please reach out to us via [Discordlink] or [mailto:team@suborbital.dev link] so we can learn how you're using it!`

- [x] In the [Embed bundle](https://suborbital.github.io/docs/atmo/usage/deploying-atmo#embed-bundle) section, we say `you can use a Dockerfile similar to this`, but it should instead say `you can use the Dockerfile that was created for your project by Subo`.

- [x] On the 'Handling requests' page, let's move 'state' to the bottom and not use it in the example at the top (things like URL and Method are more important)

- [x] Maybe we should change 'HTTP Requests' to be 'HTTP client'? To differentiate it from handling requests. And `GraphQL client` to match

- [x] I'm torn on `Authentication`, it feels like it should be up in the `usage` section.

- [x] On the 'Accessing cache' page, let's link back to the 'Connections' page to show where they can configure Redis etc.

- [x] Let's split up Sat into three pages: `Using Sat`, `Building Sat`, and `Constellations`.

**Comment by ramonh** [comment]
Hope it's fine, I edited the issue to use checkboxes so I could track as I knock these out :)

**Comment by LauraLangdon** [comment]
>Let's change By default, Rust will be used. To use Swift, pass --lang to instead use JavaScript as the alternative?

Waiting until we can try Javascript from the newest subo release before addressing.

**Comment by ramonh** [comment]
> > Let's change By default, Rust will be used. To use Swift, pass --lang to instead use JavaScript as the alternative?
> 
> Waiting until we can try Javascript from the newest subo release before addressing.

Now that `subo` is live on homebrew, this last outstanding task can be tackled, handling this today!
