### ISSUE TITLE
Improve accessibility of links

### ISSUE THREAD

**Issue by javorszky** [suborbital/docs#40]
this page: https://suborbital.github.io/docs/compute/quickstart/write-functions

accessibility niggle: when linking to things, it's better to make the actual description of what we're linking to, rather than "click here"

> Complete documentation for each of the URL parameters can be found here.

This might be better as

> You can read more about the <a>complete documentation for each of the URL parameters here</a>.

source: https://webaim.org/techniques/hypertext/link_text

**Comment by LauraLangdon** [comment]
I will absolutely defer to @javorszky here because I'm totally new to optimizing for accessibility, but I don't think I understand the issue (and I'd like to!). Both versions of the wording here seem to be fully descriptive of what we're linking to, and *both* seem to be more verbose than is described as ideal in the linked article about link text:

> Avoid uninformative link phrases
>Links are more useful when they make sense out of context. Authors should avoid non-informative link phrases such as:
>
>click here
>here
>more
>read more
>link to [some link destination]
>info
>
>In fact, the phrase "click here" is unnecessary, even if it precedes a more meaningful phrase. For example, a link that says "click here to access today's weather" can be shortened to "today's weather." In some cases it may make sense to precede a link phrase with "more" or "read more about," (e.g. "more about global warming"), but if these extra words can be avoided, it is probably best to avoid them (e.g. "global warming" may convey the same meaning as "more about global warming," depending on the context).

By my reading of the above, the only way in which the existing link text is suboptimal is that the words "can be found here" could be considered unnecessary. I'd argue they *are* necessary to maintain the narrative flow, though.

How can I understand this better so I can keep it in mind in future?

**Comment by javorszky** [comment]
A really good way to test this is to run the links through screen reader software. Mac has the built in Voiceover utility which will teach you how links work. If you enable and go through the quickstart, towards the end (18/22) you will have a section on how to navigate web pages, what does the Rotor do, and how it handles links.

In particular, enabling the rotor will gather all the links into a group and allow you to jump to them without any other context of the rest of the page. Close your eyes and listen to what voiceover will tell you about the links.

For example the two links would be announced such: <a href="#">click here</a>, and the other link would be <a href="#">the answer to the ultimate question</a>.

These two would be announced as:

> link, click here
> link, the answer to the ultimate question

Between the two, you know what will happen if you select the "link, the answer to the ultimate question", but have no idea why you should click there, or what it will do, because additional context is stripped from it.

**Comment by LauraLangdon** [comment]
Thanks so much! I'll check out the Voiceover utility. 😄

**Comment by LauraLangdon** [comment]
Okay, I've gone through the docs in order, starting from the "Intro to WebAssembly" page and going through all of the Compute pages. I'll work on the rest over the next week or two.
