### ISSUE TITLE
Review documentation around compute REPL and actual usage

### ISSUE THREAD

**Issue by javorszky** [suborbital/docs#41]
https://suborbital.github.io/docs/compute/quickstart/run-compute-locally#repl

> you will be prompted to start a REPL:

In my experience I'm dropped into the REPL without asking, or if the docs are referring to the Press enter to launch the local Compute REPL, then... I don't know what other choices I have besides hard exiting with a CTRL-C

**Comment by LauraLangdon** [comment]
> > you will be prompted to start a REPL:
> 
> In my experience I'm dropped into the REPL without asking, or if the docs are referring to the Press enter to launch the local Compute REPL, then... I don't know what other choices I have besides hard exiting with a CTRL-C

So are you feeling like the statement should give more information, or is there something else you'd like to see here?

**Comment by javorszky** [comment]
I think the documentation is inaccurate here. I'm not prompted to start a REPL, I am placed into one immediately. My hesitation is I don't know whether I have the correct words for what's happening or whether what I mean by the words is what other people mean by those words.

**Comment by LauraLangdon** [comment]
> I think the documentation is inaccurate here. I'm not prompted to start a REPL, I am placed into one immediately. My hesitation is I don't know whether I have the correct words for what's happening or whether what I mean by the words is what other people mean by those words.

![image](https://user-images.githubusercontent.com/48335772/161867929-93724820-d39b-42c5-b626-dec489d4ad1e.png)

So @javorszky I think you're referring to the "Press enter to launch the local Compute REPL..." instruction at the bottom of the image above, and seeing that in the context of the doc's statement "When you first launch Compute, you will be prompted to start a REPL," right?

Would it sit better with you if that sentence in the docs instead said "When you first launch Compute you will be prompted to press enter, which will start a REPL?"

**Comment by javorszky** [comment]
Prompt, to me at least, means I have a choice. I can choose not to. Here I don't really have a choice, I can either press enter, which will launch the REPL, press anything else which will do nothing (I think), or CTRL+C out of it.

The prompt to launch the REPL is unnecessary as it is without something else. I think the two possible solutions here are:
* drop me into REPL automatically
* offer to drop me into the REPL automatically when I press Enter, or exit out if I press Esc. CTRL+C implies something has gone wrong and I'm terminating a script halfway through what it was doing

Thinking about it it's an application issue rather than a documentation issue.

Also that dropping into the REPL happens on every launch of compute, not just the first, though I can't test (different issue).

I think documentation could sound like

> When you run Compute, it will wait for your input to start a REPL where you can add / edit functions.

**Comment by LauraLangdon** [comment]
> I think documentation could sound like
> 
> > When you run Compute, it will wait for you to press enter to start a REPL where you can add / edit functions.

Works for me!
