### ISSUE TITLE
Standardized project links and logos

### ISSUE THREAD

**Issue by cohix** [suborbital/docs#49]
Each project should have a standardized link for the 'main page', such as:
`/atmo/about`
`/sat/about`
or just
`/atmo`
`/sat`

etc

The page this loads should include the project logo so it isn't just text.

**Comment by LauraLangdon** [comment]
Were the links fixed in the last couple of hours? I started to work on them and then pulled again and now they seem to be standardized.

**Comment by cohix** [comment]
@LauraLangdon yes that's my bad, I forgot to tag the issue in my PR. This has been fixed :)
