### ISSUE TITLE
Laura's nitpicks during onboarding

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#53]
- [x] On README.md under “Using this repository” it says you’ll be using Docusaurus, but under “Prerequisites” Git, Nodejs, and Yarn are listed as needing to be installed while Docusaurus is not. So I wondered for a minute whether I needed to install Docusaurus, but in fact Docusaurus “comes with” npm, which could be worth stating explicitly.

- [x] - Under “Running the website locally” it says we need to run
    
    `cd docs/website
    npm run build
    npm run serve`
    
    But there’s a step missing, and it should instead read
    
    `cd docs/website`
    
    `npm install` (this was the missing step)
    
    `npm run build`
    
    `npm run serve`

- [ ] - In the image below, should it be clear that the text in the lower box will be generated by the terminal when `subo build .`finishes? It’s mostly clear, but the copy button in the corner throws it into question slightly. I think this is determined by some kind of styling infrastructure, but I'm not sure exactly where. But maybe there is/could be a distinct way to show code that isn’t being provided for the user to coy and use as input on their end, just for the sake of maximal clarity?) This probably happens in more places than just this one.
![image](https://user-images.githubusercontent.com/48335772/156259579-79522f4b-2c4c-4ab3-9475-43ce5748fed6.png)

**Comment by LauraLangdon** [comment]
I've taken care of the first two, but the last is kind of a style question, and also I don't know where the styling lives so I would need some guidance to fix it.

**Comment by ramonh** [comment]
Thanks for pointing these out, Laura! 

Did some poking around, found [this](https://stackoverflow.com/a/70770033).

This seems fairly doable (Also, I had no idea that adding text next to the backticks was essentially giving it a class 🤯 )

Happy to give this a shot!
