### ISSUE TITLE
Tweaks on behalf of newbies

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#58]
- [x] For the "Intro to WebAssembly" section, switch the order of "History of the Internet" and "Why WebAssembly?" because the latter is a question most new users will have and the former could lose folks who think they should proceed through resources in the order given (whether we think they "should" think they need to do that doesn't matter; we don't want to lose—exclude—people over it).

- [x] Also in the "Intro to WebAssembly" section: do we want to link to outside resources like these?

 - [x] #62

**Comment by LauraLangdon** [comment]
I'd love to hear your thoughts on the second and third items @flaki @ramonh (or anyone!). 😄

**Comment by flaki** [comment]
We should find some time to talk through improvements to the Intro to Wasm section this week, I think given the current month's focus on introductory WebAssembly content it would be a good goal to improve that section in the coming weeks!
