### ISSUE TITLE
Expose a Runnable API support grid for all languages

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#67]
Currently "not all supported languages" in Reactr are created equal. There are differences between supported [Runtime APIs](https://docs.suborbital.dev/atmo/runnable-api/introduction/), especially on preview/beta languages.

I would imagine such a "language support grid" to be similar to [caniuse.com](https://caniuse.com/fetch) — with the rows of the table representing various Runtime API features, grouped by the API (that is, various methods of the `req` request handling API would be individually present), while the columns would be the supported languages (Tiny Go, JS/TS etc.).

The (potentially color-coded) cells would refer to the [Reactr version](https://github.com/suborbital/docs/issues/23) in which a given API became available for use in the respective languages, and would present an opportunity for further notes/comments on support such as it is in the above linked page.

Another example of this pattern is the [MDN browser compatibility tables](https://developer.mozilla.org/en-US/docs/Web/API/fetch#browser_compatibility) which are also sourced from [structured data](https://github.com/mdn/browser-compat-data).

![image](https://user-images.githubusercontent.com/2089432/160744854-aebdbe79-cd11-42f6-903a-dd516adbb37c.png)

- [ ] We should add per-language support tables for Reactr Runnable APIs (e.g. to the [Language Support docs](https://discord.com/channels/808215368342044692/931576040789274645/951618082001018910)) to make it easier to expose this information to our users, but also to the developers themselves.

- [ ] We should also take steps to link the cells of missing support with tracking issues, and even automate the generation and maintenance of this information through automated sourcing of the API information from the relevant Reactr files and through automated testing.

**Comment by LauraLangdon** [comment]
I think resolving the first subissue would answer the question I needed answered in order to close Issue #22. I don't know how to create such a table myself, but I'd love to pair with someone on it or just watch! Same for the second subissue. @ramonh or @flaki, interested? :)

**Comment by flaki** [comment]
I will expand the original issue description to better explain what this issue is set out to provide, apologies for the brevity of the original filing, it was just a quick issue I jotted down from @jagger27's idea on Discord.

The TL;DR is that we want an "API support grid" that lists all supported languages and all existing Runtime APIs, and shows whether those APIs are supported in the given language. As such, it is preferred that this "language support grid" is stored as structured data, and presented from this structured data, but initially we can create a manual version to experiment with the idea.
