### ISSUE TITLE
Improving the UX of the Docusaurus navigation

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#7]
The navigation bar currently contains too many accordions (collapsed levels of content), which makes it arduous and hard to navigate.

It was proposed that, as a first measure, some items on higher levels of nesting should be initially, or even permanently expanded: 
![docs-expanded](https://user-images.githubusercontent.com/2089432/148422733-6c974444-d713-4247-8dec-971186462bab.png)

The complexity of nesting may also be amended and simplified, if and where it makes sense, this is ongoing work as the content itself evolves.

**Comment by flaki** [comment]
Entries in the sidebar can be specified as [non-collapsible](https://docusaurus.io/docs/sidebar/items#collapsible-categories) by adding extra parameters to the `sidebar.json`

![image](https://user-images.githubusercontent.com/2089432/151256374-d6f51848-604d-4d86-891d-6cb15a8e8f5a.png)

```js
module.exports ={
  docs: [
    'suborbital-ecosystem/the-suborbital-ecosystem',
    {
      type: 'category',
      label: 'Intro to WebAssembly',
      collapsible: false,
      items: [
        'intro-to-webassembly/history',
        'intro-to-webassembly/why-webassembly'
      ]
    },
// ...
```

If instead we want to have certain items be _collapsible but expanded-by-default_ we might need to write a plugin to expand sidebar configuration and translate this configuration into [state handler changes](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/utils/docSidebarItemsExpandedState.tsx).

**Comment by flaki** [comment]
#15 made various improvements to this but I'm still not satisfied with the sidebar, nor from a taxonomical point of view nor from a general usability point of view. I'll need more research in particular on how other Docusaurus-based sites use the categorization and headings as those especially leave something to be desired. Many of the subcategory pages have uninformative titles without the parent category's name, fixing this will need a bit more digging.

Also would like to explore something where we fold up all main categories where one category is selected (e.g. close all of Grav, Reactr, Vektor, Compute, Sat when Atmo is selected), which affords us extra vertical real estate in the sidebar without additional scrolling.

**Comment by flaki** [comment]
Noticed that the [docusaurus website](https://docusaurus.io/docs/) (itself built in Docusaurus) collapses the categories when the user opens another one, exactly the feature I was describing!
As it turns out, this is theme feature, enabled by setting [`autoCollapseSidebarCategories`](https://docusaurus.io/docs/sidebar#auto-collapse-sidebar-categories) to `true` in the theme config.

**Comment by flaki** [comment]
Docusaurus also comes with a second sidebar on the right, this is an in-page navigation for the headings within the active page (H2-H6).
![Docusaurus floating TOC sidebar](https://user-images.githubusercontent.com/2089432/153080649-e097e13d-17c4-4cc8-a823-83939844c228.png)

It is also possible to [inline this table of contents](https://docusaurus.io/docs/markdown-features/inline-toc) (as it is not always displayed, e.g. hidden on small screens).

Either way with the above collapsing technique and this, it might be worth considering to reduce the depth of the categorization in the sidebar, merging multiple documents which formed a whole category together into a single page of content. Of course, if later the content grows we may choose to split these pages up again.

**Comment by LauraLangdon** [comment]
This seems to be resolved, so I'm closing it. We can always revisit this after the website redesign.
