### ISSUE TITLE
Missing subo "Getting Started" page

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#76]
The [subo landing page in the docs](https://docs.suborbital.dev/subo/#getting-started) refers to a ["Getting Started" page](https://docs.suborbital.dev/subo/docs/get-started.md) that doesn't exist. Should we remove the reference or create the missing page?

**Comment by ramonh** [comment]
My guess is it's referring to the "Get Started" section from [Atmo docs](https://docs.suborbital.dev/atmo/get-started).

Happy to fix this if so!
