### ISSUE TITLE
Add Algolia search support

### ISSUE THREAD

**Issue by jagger27** [suborbital/docs#78]
It would be nice to have built-in search for our documentation. Docusaurus has (supposedly) easy to integrate search support through Algolia.

See: https://docusaurus.io/docs/search
See: https://docsearch.algolia.com/apply/

Related: #23 (consider search engine desync)

**Comment by LauraLangdon** [comment]
I've put this on the [agenda for this week's dev rel meeting](https://www.notion.so/suborbital/DevRel-Meeting-Mar-17-0f2fd84f134c46d3a668741330335eed#6d82566d688d4954a47d11c713a65be6)!

**Comment by LauraLangdon** [comment]
Closed by PR #126
