### ISSUE TITLE
Tables in docs

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#80]
Markdown tables do not seem to be enabled in Docusaurus which breaks the copy-paste of the [subo readme](https://docs.suborbital.dev/subo/#platforms). We should figure out if we want to enable them or change that table.

**Comment by ramonh** [comment]
This is odd, I was able to add them in the [Glossary](https://docs.suborbital.dev/atmo/concepts/glossary).

Let's take a looksie

**Comment by ramonh** [comment]
Ok as I feared, the markdown formatting breaks when there is no extra new line between the previous paragraph and the table declaration. 

Opening a PR shortly
