### ISSUE TITLE
contributing.md globally

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#82]
- [x] @ramonh and I were looking at Issue #5 and since all of the contributing.md pages in each repo are identical (I think), is there a way to write one contributing.md and have all the others point to it so that we can update just one instead of however many public repos we have? 

EDIT: We have *24* public repos! Not all of them have a `contributing.md` page (including the docs repo itself, LOL), and they're *not* all identical The [Sat one](https://github.com/suborbital/sat/blob/main/CONTRIBUTING.md) has Hacktoberfest info in it, which we probably don't need in March. 😁 

Currently all of the `contributing.md` pages link to the [Contributor Covenant Code of Conduct](https://github.com/suborbital/meta/blob/master/CODE_OF_CONDUCT.md) page in the meta repo. Maybe we could maintain a canonical `contributing.md` page in the meta repo, and link to that in each repo's README?

- [x] Using [subo's contributing.md](https://github.com/suborbital/subo/blob/main/CONTRIBUTING.md) as a reference, it seems like we should remove the reference to Slack and also add links to our Discord and Twitter.

- [ x] ~~The ["Contributing to Suborbital"](https://docs.suborbital.dev/contributing-guide/contributing-to-suborbital) page on the website should also point to `contributing.md`.~~ Other way round!

This would also tie into Issue #3.

**Comment by ramonh** [comment]
I'm in favour the idea of consolidating all the content into a single file, maybe here in the docs repo?

We could keep the old `contributing.md` files around, having them point here?

**Comment by flaki** [comment]
I don't think it's technically possible to replicate a single `CONTRIBUTING.md` into all our repos, but we could just replace them with a generic `CONTRIBUTING.md` that rarely changes and references a stable URL in our docs, as this content should live in the docs *anyway* IMO, and as long as most changes happen in the docs we'd just need to update the repos once.

**Comment by LauraLangdon** [comment]
>I'd prefer if that linked directly into the docs to the dedicated contributor page.

Yep! I was referring to this:

>Maybe we could maintain a canonical `contributing.md` page in the meta repo, and link to that in each repo's README?
