### ISSUE TITLE
Expose contribution docs on `/contribute`

### ISSUE THREAD

**Issue by flaki** [suborbital/docs#97]
We should expose the contribution docs at `docs.suborbital.dev/contribute`, which should serve as a landing page for people (e.g. coming from the link in CONTRIBUTE.md). We should make this a category and later expand on it.

The only way to get Docusaurus to play nice with this seems to be following how `atmo`'s similar page is laid out:
![image](https://user-images.githubusercontent.com/2089432/160050594-f5a77111-313b-4844-b03b-34efa70544db.png)

The `items: [...]` part seems necessary as long as we don't have further content pages so the cover page and category shows up, but once we have more pages the guidelines page may be removed.

**Comment by flaki** [comment]
This is a follow-up to #93

**Comment by LauraLangdon** [comment]
I have this ready, but can't check that it's displaying correctly until PR #98 is merged, I think.
